server:
  port: 8080

spring:
  application:
    name: iron-jelly
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
jwt:
  issuer: iron-jelly
  secret: nacechrn98a3912y41231
  expirationHours: 24

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG