server:
  port: 8080
spring:
  application:
    name: iron-jelly
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: iron_jelly
    password: i2n3cx13ans2612a
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: iron_jelly
    password: i2n3cx13ans2612a
    driver-class-name: org.postgresql.Driver