on:
  pull_request:
    types: [closed]

jobs:
  delete_branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Delete branch after merge
      uses: octokit/request-action@v2.x
      with:
        route: DELETE /repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
